//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pssm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pssm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        internal static string AddOK {
            get {
                return ResourceManager.GetString("AddOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员不能被禁用 的本地化字符串。
        /// </summary>
        internal static string AdiminNotDisable {
            get {
                return ResourceManager.GetString("AdiminNotDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员不能被删除 的本地化字符串。
        /// </summary>
        internal static string AdminNotDelte {
            get {
                return ResourceManager.GetString("AdminNotDelte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteSucce {
            get {
                return ResourceManager.GetString("DeleteSucce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用成功 的本地化字符串。
        /// </summary>
        internal static string DisableSucce {
            get {
                return ResourceManager.GetString("DisableSucce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用成功 的本地化字符串。
        /// </summary>
        internal static string EnableSucce {
            get {
                return ResourceManager.GetString("EnableSucce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已经运行 的本地化字符串。
        /// </summary>
        internal static string FromIsTwo {
            get {
                return ResourceManager.GetString("FromIsTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是禁用转态 的本地化字符串。
        /// </summary>
        internal static string ISDisable {
            get {
                return ResourceManager.GetString("ISDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是启用转态 的本地化字符串。
        /// </summary>
        internal static string IsEnable {
            get {
                return ResourceManager.GetString("IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单前父节点有子节点未删除，无法删除 的本地化字符串。
        /// </summary>
        internal static string ISParentID {
            get {
                return ResourceManager.GetString("ISParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftMenu.xml 的本地化字符串。
        /// </summary>
        internal static string LeftMenu {
            get {
                return ResourceManager.GetString("LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确认删除 的本地化字符串。
        /// </summary>
        internal static string OKDelete {
            get {
                return ResourceManager.GetString("OKDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录系统 的本地化字符串。
        /// </summary>
        internal static string OpertypeLogin {
            get {
                return ResourceManager.GetString("OpertypeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string PassIsNull {
            get {
                return ResourceManager.GetString("PassIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSucce {
            get {
                return ResourceManager.GetString("SaveSucce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要修改的账号 的本地化字符串。
        /// </summary>
        internal static string SeachUser {
            get {
                return ResourceManager.GetString("SeachUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        internal static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认要初始化系统吗？系统初始化要清空所有数据 的本地化字符串。
        /// </summary>
        internal static string SystemInitialize {
            get {
                return ResourceManager.GetString("SystemInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次输入密码不匹配 的本地化字符串。
        /// </summary>
        internal static string TwoPass {
            get {
                return ResourceManager.GetString("TwoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或密码错误 的本地化字符串。
        /// </summary>
        internal static string UsePawErroy {
            get {
                return ResourceManager.GetString("UsePawErroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不存在 的本地化字符串。
        /// </summary>
        internal static string UserIsExitis {
            get {
                return ResourceManager.GetString("UserIsExitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不能为空 的本地化字符串。
        /// </summary>
        internal static string UserIsNull {
            get {
                return ResourceManager.GetString("UserIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆成功 的本地化字符串。
        /// </summary>
        internal static string UserSuccer {
            get {
                return ResourceManager.GetString("UserSuccer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 密码 {
            get {
                object obj = ResourceManager.GetObject("密码", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 猪 {
            get {
                object obj = ResourceManager.GetObject("猪", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 登录 {
            get {
                object obj = ResourceManager.GetObject("登录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 登陆背景 {
            get {
                object obj = ResourceManager.GetObject("登陆背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 账号 {
            get {
                object obj = ResourceManager.GetObject("账号", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 退出 {
            get {
                object obj = ResourceManager.GetObject("退出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
